
$file = "C:\Users\kalhe\Documents\antigravity\hopeful-pythagoras\lingua\data.js"
$content = Get-Content $file -Raw -Encoding UTF8

$newPhrasal = @'
const PHRASAL = [
  {pv:"bring up",sep:"sep",meaning:"To mention or introduce a topic in conversation; also to raise a child.",am:"ርዕስ ማንሳት / ልጅ ማሳደግ",examples:["Why did you have to bring up the salary issue right in the middle of the celebration dinner?","She was brought up in a small rural village but later became one of the country's most prominent scientists."]},
  {pv:"bring about",sep:"insep",meaning:"To cause something to happen; to make a significant change occur.",am:"ነገርን ማምጣት / ለውጥ ማድረስ",examples:["The industrial revolution brought about the most dramatic transformation in human working conditions in history.","What factors brought about the sudden collapse of that once-dominant company?"]},
  {pv:"carry out",sep:"sep",meaning:"To complete or perform a task, plan, or instruction.",am:"ተግባር ማከናወን / ትዕዛዝ ማስፈጸም",examples:["The research team carefully carried out dozens of experiments before publishing their groundbreaking findings.","She carried out every responsibility assigned to her with exceptional precision and dedication."]},
  {pv:"come across",sep:"insep",meaning:"To encounter or find by chance; how you appear or seem to others.",am:"በአጋጣሚ ማግኘት / ለሌሎች መታየት",examples:["I came across a fascinating article about language acquisition while researching for my essay.","She comes across as extremely confident in presentations, even though she is actually quite anxious inside."]},
  {pv:"come up with",sep:"insep",meaning:"To think of or produce an idea, plan, or solution.",am:"ሐሳብ ወይም መፍትሔ ማምጣት",examples:["After three sleepless nights, she finally came up with an innovative solution to the technical problem.","Can you come up with a better argument than the one you presented in your first draft?"]},
  {pv:"cut down on",sep:"insep",meaning:"To reduce the amount or frequency of something you do or consume.",am:"መጠን ወይም ድግግሞሽ መቀነስ",examples:["The doctor strongly advised him to cut down on sugar and processed food immediately.","She cut down on social media time and found she had hours of productivity she didn't know she was missing."]},
  {pv:"deal with",sep:"insep",meaning:"To take action to solve a problem or handle a difficult situation.",am:"ችግር ማስተናገድ / መቆጣጠር",examples:["The ability to deal with pressure calmly and rationally is one of the most valuable professional skills you can develop.","She has had to deal with enormous adversity throughout her life, and she has grown stronger through all of it."]},
  {pv:"draw on",sep:"insep",meaning:"To use knowledge, experience, or resources for a specific purpose.",am:"እውቀትን ወይም ልምድን ለዓላማ መጠቀም",examples:["In her presentation, she drew on over two decades of fieldwork experience to support her arguments.","Great writers draw on their deepest personal experiences to create stories that resonate universally."]},
  {pv:"fall behind",sep:"insep",meaning:"To fail to keep up with a schedule, standard, or group.",am:"ከደረጃ ወይም ከቡድን ወደ ኋላ ቀርቶ",examples:["If you miss too many classes, you will quickly fall behind and struggle to catch up with the rest of the group.","The company fell behind its competitors by failing to invest in new technology early enough."]},
  {pv:"figure out",sep:"sep",meaning:"To understand or solve something after thinking carefully.",am:"ከጥልቅ ሐሳብ በኋላ ነገርን መረዳት",examples:["She eventually figured out why her essay wasn't working and completely rewrote it from scratch.","I cannot figure out how to properly use the present perfect versus the past simple — could you explain?"]},
  {pv:"get across",sep:"sep",meaning:"To communicate an idea or message successfully so others understand it.",am:"ሐሳብ ወይም መልዕክት በተሳካ ሁኔታ ማስረዳት",examples:["The key challenge in academic writing is getting your complex ideas across clearly and concisely.","She struggled to get her point across until she used a concrete real-world example."]},
  {pv:"get along",sep:"insep",meaning:"To have a friendly, harmonious relationship with someone.",am:"ከሰዎች ጋር ጥሩ ግንኙነት ማድረግ",examples:["Despite their very different personalities, the two co-founders got along remarkably well for years.","Learning to get along with people you fundamentally disagree with is a crucial life skill."]},
  {pv:"get away with",sep:"insep",meaning:"To escape punishment or consequences for something you did wrong.",am:"ከቅጣት ሳይደርስ ማምለጥ",examples:["He cheated on the exam and got away with it this time, but that kind of dishonesty eventually catches up with you.","Don't assume that submitting plagiarized work will allow you to get away with it undetected."]},
  {pv:"give up",sep:"sep",meaning:"To stop doing something; to abandon a habit or goal.",am:"መተው / ዓላማ ወይም ልምድ ማቆም",examples:["She refused to give up on her dream of becoming a doctor despite failing the entrance exam twice.","He finally gave up smoking after twenty years when his doctor delivered the sobering health diagnosis."]},
  {pv:"go through",sep:"insep",meaning:"To experience something difficult; to examine something carefully.",am:"ፈታኝ ሁኔታ ማለፍ / ጥንቃቄ ያለው ፍተሻ ማካሄድ",examples:["She went through an incredibly challenging period after losing her job and home in the same month.","Before submitting your essay, go through it carefully at least three times looking for errors."]},
  {pv:"grow up",sep:"insep",meaning:"To develop from a child to an adult; to start behaving maturely.",am:"ከልጅነት ወደ ትልቅነት ማደግ / ጎልማሳ ሁናቴ ማሳየት",examples:["She grew up in Addis Ababa and moved to Europe to pursue her master's degree at twenty-three.","Grow up and take responsibility for your actions — blaming everyone else solves absolutely nothing."]},
  {pv:"hold on",sep:"insep",meaning:"To wait; to keep firmly; to survive a difficult period.",am:"መጠበቅ / ጽናት ማሳየት",examples:["Hold on — before you make that decision, let me share some information that might change your perspective.","The small business had to hold on through three incredibly difficult years before becoming profitable."]},
  {pv:"keep up with",sep:"insep",meaning:"To maintain the same pace or level as someone or something else.",am:"ከሌሎች ጋር ፍጥነት ወይም ደረጃ ማስጠበቅ",examples:["Reading a newspaper in English every morning is an excellent way to keep up with both current events and vocabulary.","It is increasingly difficult to keep up with the rapid pace of technological innovation in the digital age."]},
  {pv:"let down",sep:"sep",meaning:"To disappoint someone by failing to meet their expectations.",am:"ተስፋ ማሳጣት / ከቃልኪዳን ማፈንገጥ",examples:["Please don't let me down — I vouched for your reliability and the whole team is counting on you.","She felt deeply let down when her mentor failed to show up to her most important presentation."]},
  {pv:"look into",sep:"insep",meaning:"To investigate or research something in detail.",am:"ጥልቅ ምርምር ወይም ፍተሻ ማካሄድ",examples:["The committee agreed to look into the allegations of financial misconduct at the highest level.","She decided to look into the benefits of mindfulness after reading about its impact on productivity."]},
  {pv:"look up to",sep:"insep",meaning:"To admire and respect someone greatly.",am:"ሰውን ከፍ አድርጎ ማክበርና ማድነቅ",examples:["She has always looked up to her grandmother, who overcame extraordinary adversity with grace and dignity.","Young people need positive role models they can genuinely look up to in their communities."]},
  {pv:"make up for",sep:"insep",meaning:"To compensate for something; to do something to improve a bad situation.",am:"ካለፈ ስህተት ወይም ጉዳት ካሳ መስጠት",examples:["He worked extra hours every weekend to make up for the time he had wasted at the beginning of the project.","No amount of money can ever make up for the loss of years spent in a career that doesn't fulfill you."]},
  {pv:"move on",sep:"insep",meaning:"To start a new chapter after something has ended; to stop dwelling on the past.",am:"ያለፈ ነገርን ትቶ ወደ ፊት ማለፍ",examples:["After years of grief, she finally began to move on and rebuild her life with remarkable courage.","The best thing you can do after failure is learn from it and move on without bitterness."]},
  {pv:"pick up",sep:"sep",meaning:"To acquire a skill or habit gradually; to collect someone; to improve.",am:"ቀስ ብሎ ክህሎት ማዳበር / ሁኔታ መሻሻል",examples:["She picked up fluent Spanish in just eighteen months by immersing herself completely in the language.","Business has started to pick up again after a very slow first quarter."]},
  {pv:"point out",sep:"sep",meaning:"To draw attention to something specific; to indicate or mention.",am:"ልዩ ነጥብ ላይ ትኩረት መሳብ / ማሳወቅ",examples:["Several reviewers pointed out that the study had a significant methodological flaw in its design.","She kindly pointed out that I had misspelled 'necessary' in three different places in my essay."]},
  {pv:"put off",sep:"sep",meaning:"To postpone or delay something; to cause someone to lose interest.",am:"ነገርን ማዘግየት / ፍላጎት ማጣት",examples:["Stop putting off the most difficult tasks — tackle them first while your energy and focus are highest.","The aggressive sales approach actually put many potential customers off completely."]},
  {pv:"run into",sep:"insep",meaning:"To encounter by chance; to meet unexpectedly.",am:"ሳይጠበቅ ሰውን ወይም ችግር ማጋጠም",examples:["I ran into my university professor at the airport — it was a complete and wonderful coincidence.","Every new project runs into unexpected obstacles; how you handle them defines the outcome."]},
  {pv:"run out of",sep:"insep",meaning:"To use up a supply until nothing remains.",am:"አቅርቦት ሙሉ ለሙሉ ማለቅ",examples:["She ran out of ideas halfway through the essay and decided to step away and return with fresh eyes.","We're running out of time to address the climate crisis before irreversible damage is done."]},
  {pv:"set up",sep:"sep",meaning:"To establish, arrange, or create something new.",am:"አዲስ ነገር ማዘጋጀት ወይም መመስረት",examples:["She set up her own consultancy firm at 29, just five years after graduating from university.","Could you help me set up the equipment before the presentation? The speakers aren't working properly."]},
  {pv:"stand out",sep:"insep",meaning:"To be noticeably different or better than others.",am:"ከሌሎች ልዩ ሆኖ መጎልጎል / ማስተዋል",examples:["What makes her application stand out is the combination of academic excellence and real-world experience.","A polished writing style will immediately make your work stand out to any examiner or employer."]},
  {pv:"take on",sep:"sep",meaning:"To accept or begin to tackle a new responsibility or challenge.",am:"አዲስ ኃላፊነት ወይም ፈታኝ ሥራ መቀበል",examples:["She took on the role of project leader despite having no formal management training whatsoever.","The company decided to take on fifty new employees to handle the unexpected surge in demand."]},
  {pv:"take over",sep:"sep",meaning:"To assume control or responsibility of something from someone else.",am:"ከሌላ ሰው ቁጥጥር ወይም ኃላፊነት ማረፍ",examples:["His daughter took over the family business at 28 and transformed it into a global operation.","Automation is threatening to take over many jobs that humans have performed for generations."]},
  {pv:"turn around",sep:"sep",meaning:"To change a failing situation into a successful one; to reverse direction.",am:"ወደ ውድቀት የሄደ ሁኔታ ወደ ስኬት መቀልበስ",examples:["The new CEO turned the company around within eighteen months, returning it to record profitability.","When everything feels hopeless, sometimes one good decision can turn your entire life around."]},
  {pv:"turn down",sep:"sep",meaning:"To refuse or reject an offer, request, or opportunity.",am:"ሀሳብ ወይም ዕድል መ거부ቡ",examples:["She turned down a lucrative job offer in New York because she didn't want to leave her family.","He was turned down from every program he applied to before finally being accepted on his fifth attempt."]},
  {pv:"work out",sep:"sep",meaning:"To exercise; to resolve a problem; to happen successfully in the end.",am:"ስፖርት ማድረግ / ችግር መፍታት / በሚጠበቀው መልኩ ማለቅ",examples:["Even if a relationship doesn't work out, every experience teaches you something valuable about yourself.","She works out for one hour every morning before starting her intensive twelve-hour workday."]},
  {pv:"back down",sep:"insep",meaning:"To withdraw from a position or stop demanding something.",am:"ከቆሙበት አቋም ወደ ኋላ ማፈግፈግ",examples:["Despite pressure from all sides, she refused to back down from her principled stance.","He eventually backed down when he realized the evidence was completely against him."]},
  {pv:"break down",sep:"sep",meaning:"To analyze into components; to stop functioning; to collapse emotionally.",am:"ዝርዝር ማድረግ / ስሜታዊ ወይም ሜካኒካዊ ውድቀት",examples:["Let me break down the structure of a strong argumentative essay into five clearly defined components.","She broke down completely when she received the devastating news about her best friend."]},
  {pv:"break through",sep:"insep",meaning:"To achieve a major advance after a period of difficulty.",am:"ከፈታኝ ጊዜ በኋላ ትልቅ ስኬት ማሳካት",examples:["After years of rejection, she finally broke through when a major publisher accepted her novel.","Scientists are close to breaking through in their research on treatments for Alzheimer's disease."]},
  {pv:"build up",sep:"sep",meaning:"To gradually increase, develop, or accumulate something over time.",am:"ቀስ ቀስ ማሳደግ ወይም ማካበት",examples:["It takes years of consistent effort to build up the kind of vocabulary needed for advanced academic writing.","He built up a remarkable reputation through decades of integrity, honesty, and excellent work."]},
  {pv:"catch up",sep:"insep",meaning:"To reach the same level as someone else; to update on missed events.",am:"ከሌሎች ጋር ደረጃ ማሳካት / ያለፈ ዜና ማካካስ",examples:["After missing two weeks due to illness, she worked incredibly hard to catch up with the rest of the class.","Let's meet for coffee this week and catch up — I haven't heard from you in months."]},
  {pv:"close down",sep:"sep",meaning:"To stop operating or functioning permanently.",am:"ሥራ ወይም ተቋም ለዘለቄታ ማቆም",examples:["Unfortunately, the company was forced to close down after 50 years due to financial difficulties.","Three of my favorite local restaurants closed down during the economic difficulties of recent years."]},
  {pv:"count on",sep:"insep",meaning:"To rely or depend on someone or something.",am:"በሰው ወይም ነገር ላይ መደገፍ",examples:["You can always count on her — she has never missed a deadline or broken a promise in her career.","Never count on luck alone; build skills and systems you can count on even when circumstances are difficult."]},
  {pv:"drop out",sep:"insep",meaning:"To leave an educational institution or competition before finishing.",am:"ትምህርት ወይም ውድድር ሳያጠናቅቁ መልቀቅ",examples:["He dropped out of university to pursue his startup and later became one of the wealthiest people in his country.","She dropped out of the race after sustaining an injury in the opening stages of the competition."]},
  {pv:"end up",sep:"insep",meaning:"To finally reach a situation or place, often unexpectedly.",am:"ሳይጠበቅ ወደ ሁኔታ ወይም ቦታ መድረስ",examples:["She started studying law but ended up becoming a celebrated documentary filmmaker instead.","If you keep avoiding difficult conversations, you will end up with unresolved problems that grow much larger."]},
  {pv:"get over",sep:"insep",meaning:"To recover from an illness, loss, or difficult experience.",am:"ከሕመም፣喪失 ወይም ፈታኝ ሁኔታ ማገገም",examples:["It took her nearly two years to fully get over the shock and grief of losing her position.","How do you get over the fear of making mistakes when speaking a foreign language in public?"]},
  {pv:"give in",sep:"insep",meaning:"To eventually agree to something after initially refusing; to yield.",am:"ከጫናl በኋላ ተስማምቶ መቀበል",examples:["She held firm for weeks before finally giving in to the pressure and accepting their terms.","Don't give in to the temptation of shortcutting your learning — it always costs more in the long run."]},
  {pv:"go ahead",sep:"insep",meaning:"To proceed with something; to start doing something after permission is given.",am:"ፈቃድ ካገኙ በኋላ ወይም ቀጥሎ መሄድ",examples:["Once you have thoroughly reviewed the contract, please go ahead and sign the final version.","Go ahead and share your honest opinion — we specifically asked for critical feedback, not flattery."]},
  {pv:"go back on",sep:"insep",meaning:"To fail to keep a promise or commitment; to reverse a previous decision.",am:"ቃል ኪዳን ወይም ቀድሞ የተሰጠ ውሳኔ ማፍረስ",examples:["A person of integrity never goes back on their word once they have made a commitment.","The government went back on its promise to reduce taxes, causing widespread public anger."]},
  {pv:"hang on",sep:"insep",meaning:"To wait; to hold tightly; to persist through difficulty.",am:"መጠበቅ / ጽናት ሳይቀር ማለፍ",examples:["Hang on just a moment — I need to double-check this figure before I give you a definitive answer.","If you can hang on through these difficult months, the improvement will be extraordinary."]},
  {pv:"hold back",sep:"sep",meaning:"To restrain yourself or someone else; to prevent progress.",am:"ራስን ወይም ሌሎችን መግታት / ዕድገት ማሰናከል",examples:["Fear of failure is the single greatest factor that holds most talented people back from their potential.","She held back her tears during the speech and only broke down once she reached the car."]},
  {pv:"lay off",sep:"sep",meaning:"To dismiss employees; to stop doing something repeatedly requested.",am:"ሠራተኞችን ከሥራ ማሰናበት / ማቆም",examples:["The company had to lay off 500 employees due to the devastating economic impact of the global recession.","Could you please lay off the jokes during the serious sections of the presentation?"]},
  {pv:"look forward to",sep:"insep",meaning:"To feel excited and anticipate something in the future with pleasure.",am:"ወደፊት ሊሆን ካለ ነገር በደስታ መጠበቅ",examples:["I genuinely look forward to seeing how your writing improves over the next thirty days of consistent practice.","She has been looking forward to this graduation ceremony for four long and challenging years."]},
  {pv:"narrow down",sep:"sep",meaning:"To reduce a list of options to a smaller, more manageable number.",am:"አማራጮቹን ወደ ጥቂቶቹ ማሳጠር",examples:["After reviewing all fifty applications, the committee narrowed down the candidates to just six finalists.","Let's narrow down your essay topic — it's too broad to cover effectively in just 500 words."]},
  {pv:"open up",sep:"sep",meaning:"To reveal your feelings or thoughts; to create new possibilities.",am:"ስሜትን ወይም ሐሳብን መናገር / አዲስ ዕድሎችን መፍጠር",examples:["It took months of therapy before he finally felt safe enough to open up about his childhood.","Learning a second language opens up extraordinary professional and social opportunities globally."]},
  {pv:"pay off",sep:"insep",meaning:"To produce a successful result after effort; to settle a debt.",am:"ጥረት ፍሬ መስጠት / 借款 ዕዳ መክፈል",examples:["Years of disciplined study finally paid off when she received a full scholarship to her dream institution.","Every hour you invest in improving your English will pay off in ways you cannot currently imagine."]},
  {pv:"press on",sep:"insep",meaning:"To continue with something despite difficulties; to persist.",am:"ፈታኝ ቢሆንም ቀጥሎ መሄድ / ጽናት ማሳየት",examples:["Despite receiving dozens of rejections, she pressed on and submitted her manuscript to one more publisher.","Press on with your studies even during the weeks when progress seems impossibly slow."]},
  {pv:"scale up",sep:"sep",meaning:"To increase the size, scope, or rate of something significantly.",am:"ሥፋት ወይም ፍጥነት ማሳደግ",examples:["The successful pilot program was scaled up nationally after producing exceptional initial results.","As demand grew, they had to scale up production while maintaining the quality standards they were known for."]},
  {pv:"set apart",sep:"sep",meaning:"To distinguish someone or something from others; to make unique.",am:"ከሌሎች ለይቶ ማሳየት / ልዩ ማድረግ",examples:["What truly sets her apart from other candidates is her combination of technical skill and emotional intelligence.","His unique perspective, shaped by living across three continents, sets his writing completely apart."]},
  {pv:"show up",sep:"insep",meaning:"To arrive or appear somewhere; to be present consistently.",am:"ቦታ ላይ መድረስ / ሁሌ ፊት ለፊት መቅረብ",examples:["Success is not about being perfect — it is about showing up every single day and doing the work.","She showed up to every rehearsal even when she was unwell, demonstrating extraordinary professionalism."]},
  {pv:"step up",sep:"insep",meaning:"To increase one's efforts; to take on greater responsibility.",am:"ጥረትን ማሳደግ / ትልቅ ኃላፊነት ማዘዝ",examples:["When the manager resigned unexpectedly, she stepped up and led the team through a critical transition.","We all need to step up our commitment to sustainability if we want to leave a livable world for future generations."]},
  {pv:"take in",sep:"sep",meaning:"To fully understand or absorb information; to provide shelter.",am:"መረጃ ሙሉ ለሙሉ ማስተናገድ / ጥቅሉን ሰጥቶ መቀበል",examples:["The lecture was so information-dense that I couldn't take it all in and had to request a recording.","Her aunt took her in and supported her completely during the most difficult period of her life."]},
  {pv:"think through",sep:"sep",meaning:"To carefully consider all aspects of a problem or plan.",am:"ሁሉንም ገጽታዎች ጥልቅ አስቦ ማጤን",examples:["Before making any major life decision, take the time to thoroughly think it through from every angle.","She thought through every possible consequence before presenting her unconventional business strategy."]},
  {pv:"wind down",sep:"sep",meaning:"To gradually slow or reduce activity; to relax after a busy period.",am:"ቀስ ቀስ ሥራን ወይም እንቅስቃሴን ማቀዝቀዝ",examples:["After the intense exam period, students desperately need time to wind down and recover properly.","The company is slowly winding down its unprofitable international operations to focus on its core market."]},
  {pv:"zone in on",sep:"insep",meaning:"To focus intensely and precisely on something specific.",am:"ልዩ ነጥብ ላይ ጥልቅ ትኩረት ማሰብ",examples:["She has an extraordinary ability to zone in on the most critical issue in any complex situation.","The editor immediately zoned in on the structural weaknesses in the third paragraph of the essay."]},
  {pv:"zero in on",sep:"insep",meaning:"To identify and focus on something precisely; to target.",am:"ዒላማን ማስቀመጥ / ትክክለኛ ነጥብ ላይ ማተኮር",examples:["Effective learners zero in on their specific weaknesses rather than simply repeating what they already know.","The detective zeroed in on the one inconsistency in the witness's account that changed everything."]},
  {pv:"branch out",sep:"insep",meaning:"To expand into new areas or try new things.",am:"ወደ አዲስ ዘርፍ ወይም ሙከራ መዘርጋት",examples:["After ten years in accounting, she decided to branch out and train as an executive coach.","The restaurant branched out from Ethiopian cuisine and added a Mediterranean menu that proved incredibly popular."]},
  {pv:"chip away at",sep:"insep",meaning:"To gradually reduce or make progress against something large.",am:"ትልቅ ፈታኝ ነገር ቀስ ቀስ ማሳጠር / ወደ ፊት መጓዝ",examples:["She chipped away at the mountain of research material for weeks until she finally had enough for her thesis.","Every small daily improvement chips away at the gap between where you are and where you want to be."]},
  {pv:"draw up",sep:"sep",meaning:"To prepare and write a formal document or plan.",am:"ይፋዊ ሰነድ ወይም እቅድ ማዘጋጀት",examples:["The lawyers were asked to draw up a comprehensive contract covering every possible contingency.","Let's draw up a detailed revision plan so you can cover all the material systematically before the exam."]},
  {pv:"fall through",sep:"insep",meaning:"To fail to happen; to collapse before completion.",am:"ሳይጠናቀቅ ዕቅድ ወይም ስምምነት ወድቆ መቅረት",examples:["The business deal fell through at the last moment when the investor withdrew their funding.","Our plans for a group trip fell through because we couldn't find dates that worked for everyone."]},
  {pv:"flesh out",sep:"sep",meaning:"To add more detail, substance, or development to an idea or plan.",am:"ሐሳብ ወይም ዕቅድ ዝርዝር ማደርገት / ማበልጸግ",examples:["Your argument is interesting but needs to be fleshed out with specific evidence and examples.","The screenwriter spent three weeks fleshing out the characters before writing a single line of dialogue."]},
  {pv:"iron out",sep:"sep",meaning:"To resolve problems or difficulties; to smooth over disagreements.",am:"ልዩነቶችን ወይም ችግሮችን ማስታረቅ",examples:["There are still a few issues to iron out before we can present the final agreement to the board.","The two teams spent the morning ironing out the remaining differences in their proposed merger terms."]},
  {pv:"live up to",sep:"insep",meaning:"To reach the standard or fulfill the expectations that others have.",am:"ሌሎች ያስቀመጡት ደረጃ ወይም ተስፋ ማሳካት",examples:["She has consistently lived up to every expectation placed on her and exceeded most of them.","The long-awaited sequel failed to live up to the extraordinary standards set by the original film."]},
  {pv:"mark down",sep:"sep",meaning:"To reduce the price; to give someone a lower mark or score.",am:"ዋጋ መቀነስ / ዝቅ ያለ ምዘና መስጠት",examples:["Students were marked down significantly for failing to use adequate academic sources in their essays.","All seasonal items were marked down by 50% to clear stock before the new collection arrived."]},
  {pv:"pin down",sep:"sep",meaning:"To define or determine something precisely; to get a commitment.",am:"ነገርን ትክክለኛ ትርጓሜ ማስቀመጥ / ቁርጠኝነት ማሳደር",examples:["It is difficult to pin down exactly when the language began evolving so rapidly.","She was impossible to pin down to a specific date — she always said she would 'think about it'."]},
  {pv:"play down",sep:"sep",meaning:"To make something seem less important or serious than it actually is.",am:"ነገርን ያለምጥን አናሳ አድርጎ ማሳየት",examples:["She played down her extraordinary achievements out of genuine modesty, not false humility.","The government tried to play down the severity of the economic crisis but the data told a different story."]},
  {pv:"pull through",sep:"insep",meaning:"To survive a serious illness or difficulty against expectations.",am:"ተስፋ ከቆረጡ ሁኔታ ውስጥ ተዓምር ሆኖ ማምለጥ",examples:["After the devastating accident, doctors were uncertain, but she pulled through with remarkable strength.","Small businesses that survived the recession pulled through by adapting quickly and radically."]},
  {pv:"put across",sep:"sep",meaning:"To communicate or explain an idea effectively.",am:"ሐሳብ ወይም ዕቅድ ቀጥ ብሎ ማስረዳት",examples:["The best way to put complex ideas across clearly is to use concrete examples your audience recognizes.","He struggled to put his innovative idea across to investors who were resistant to unconventional thinking."]},
  {pv:"ramp up",sep:"sep",meaning:"To increase the level or intensity of something significantly.",am:"ደረጃ ወይም ጥንካሬ ፈጠን ብሎ ማሳደግ",examples:["They ramped up production by 300% to meet the unprecedented surge in consumer demand.","She ramped up her study hours significantly in the final month before the critical examination."]},
  {pv:"settle for",sep:"insep",meaning:"To accept something that is less than what you really wanted.",am:"ሙሉ ፍላጎት ሳይሟላ ያለበቃ ነገር ተቀብሎ መቀመጥ",examples:["Never settle for a life that doesn't align with your deepest values — you deserve authentic fulfillment.","Don't settle for a mediocre vocabulary; invest in it daily and the growth will be exponential."]},
  {pv:"speak out",sep:"insep",meaning:"To express your opinion boldly and publicly, often on an important issue.",am:"ድፍረት ሞልቶ ሐሳብ በይፋ መናገር",examples:["It takes genuine courage to speak out against injustice when the social cost of doing so is very high.","She was one of the first in her industry to speak out about the systemic discrimination women faced."]},
  {pv:"spring up",sep:"insep",meaning:"To appear, grow, or develop suddenly and rapidly.",am:"ድንገት ፈጣን ሆኖ ብቅ ማለት",examples:["Tech startups have sprung up in every major city around the world over the past decade.","New language schools sprang up across the country following the surge in demand for English education."]},
  {pv:"stand up for",sep:"insep",meaning:"To defend or support someone or something under pressure.",am:"ጫና ስር ሆኖ ሰው ወይም ሐሳብ ለመጠበቅ ቆሞ መከራከር",examples:["True integrity means standing up for what is right even when it is unpopular and personally costly.","She stood up for her colleague when he was being unfairly criticized in the team meeting."]},
  {pv:"tone down",sep:"sep",meaning:"To make something less extreme, intense, or offensive.",am:"ቃናን ወይም ጥንካሬን ማለዘብ",examples:["The editor asked him to tone down the political language to avoid alienating readers with different views.","She toned down her original proposal after realizing it was too ambitious for the current budget."]},
  {pv:"wear out",sep:"sep",meaning:"To become exhausted from overuse; to exhaust someone completely.",am:"ከልክ ያለፈ አጠቃቀም ሰበብ ሙሉ ለሙሉ ድካም",examples:["After three years of intense overwork, she was completely worn out and needed a serious break.","Don't wear yourself out trying to be perfect; progress and consistency matter far more than perfection."]},
  {pv:"back up",sep:"sep",meaning:"To support with evidence; to make a copy of data; to reverse.",am:"በማስረጃ ማስደገፍ / ቅጂ ማስቀመጥ",examples:["Every argument in an essay must be backed up with credible evidence and concrete examples.","Always back up your important files — losing years of work to a technical failure is devastating."]},
  {pv:"break off",sep:"sep",meaning:"To stop suddenly; to end a relationship.",am:"ድንገት ማቆም / ግንኙነት ማቋረጥ",examples:["The two countries broke off diplomatic relations following the incident at the border.","She broke off the engagement after realizing they had fundamentally incompatible life goals."]},
  {pv:"call off",sep:"sep",meaning:"To cancel something that was planned.",am:"ታቅዶ የነበረ ነገር ሰርዞ ማቆም",examples:["They were forced to call off the outdoor event due to the extremely dangerous weather conditions.","The negotiations were called off after both sides failed to reach even a basic agreement."]},
  {pv:"catch on",sep:"insep",meaning:"To become popular; to understand something after a delay.",am:"ተወዳጅ ሆኖ መስፋፋት / ዘግይቶ ነገርን መረዳት",examples:["The technique took years to catch on but is now standard practice throughout the entire industry.","It took him a while to catch on to the informal humor of his British colleagues."]},
  {pv:"check in",sep:"insep",meaning:"To register upon arriving; to contact someone to see how they are.",am:"ሲደርሱ ምዝገባ ማድረግ / ሰውን ሁኔታ ለማወቅ ማነጋገር",examples:["Please check in with me once a week to share your writing practice updates and progress.","Always check in with your mentor or support system when you're feeling overwhelmed or stuck."]},
  {pv:"come around",sep:"insep",meaning:"To change your opinion; to regain consciousness; to visit.",am:"አስተሳሰብ መቀየር / ወደ ሰዎች ሊጠይቁ መምጣት",examples:["She was initially resistant to the feedback, but she came around when she saw the results it produced.","He eventually came around to the idea of learning English when he saw how it benefited his sister's career."]},
  {pv:"dig into",sep:"insep",meaning:"To investigate thoroughly; to start eating enthusiastically.",am:"ጥልቅ ፍተሻ ማካሄድ / ምግብ ስሜት ሞልቶ ጀምሮ መብላት",examples:["The journalist spent four months digging into the corruption scandal before publishing the exposé.","After hours of cooking, it was incredibly satisfying to finally dig into the meal we had prepared."]},
  {pv:"factor in",sep:"sep",meaning:"To include a particular fact or element when making a calculation or plan.",am:"ሲሰሉ ወይም ሲያቅዱ ልዩ ሁኔታን ከግምት ውስጥ ማስገባት",examples:["When planning your English learning journey, factor in the time needed for regular review, not just new learning.","The price quoted didn't factor in delivery costs, which added 20% to the total."]},
  {pv:"hammer out",sep:"sep",meaning:"To reach an agreement after long and difficult discussion.",am:"ከረዥምና ፈታኝ ውይይት በኋላ ስምምነት ላይ መድረስ",examples:["The two sides finally hammered out a compromise after twelve grueling hours of negotiation.","The team spent weeks hammering out the details of the new curriculum before presenting it to the board."]},
  {pv:"jump at",sep:"insep",meaning:"To eagerly accept an opportunity without hesitation.",am:"ዕድል ሳያሳቡ ቀልጠፍ ብሎ መቀበል",examples:["When she was offered the chance to study abroad, she jumped at it without a moment of doubt.","Any candidate who truly wants to grow should jump at difficult opportunities, not shy away from them."]},
  {pv:"knuckle down",sep:"insep",meaning:"To start working seriously and with complete focus and determination.",am:"ሙሉ ትኩረትና ቁርጠኝነት ሞልቶ ሥራ መጀመር",examples:["The exams are only two months away — it's time to stop procrastinating and knuckle down seriously.","She knuckled down in her third year and the improvement in her grades was dramatically visible."]},
  {pv:"map out",sep:"sep",meaning:"To plan something in detail; to describe or chart a process.",am:"ዝርዝር ዕቅድ ማዘጋጀት / ሂደት ቅደም ተከተል ማሳየት",examples:["Before writing your essay, take ten minutes to map out your main arguments and supporting evidence.","She carefully mapped out her five-year career plan including specific milestones and timelines."]},
  {pv:"nail down",sep:"sep",meaning:"To define or determine something clearly and with precision.",am:"ነገርን ትክክለኛ ሆኖ ማስቀመጥ / ዝርዝር ማረጋገጥ",examples:["It's difficult to nail down exactly what makes one piece of writing great and another merely competent.","Let's nail down the core objectives of the project before we start assigning tasks to team members."]},
  {pv:"reach out",sep:"insep",meaning:"To make contact with someone to offer or request help.",am:"ሌሎችን ለመርዳት ወይም እርዳታ ለመጠየቅ ማነጋገር",examples:["Don't hesitate to reach out to native English speakers online — most are delighted to help learners.","She reached out to her network and found the opportunity she had been looking for within two weeks."]},
  {pv:"sink in",sep:"insep",meaning:"To be fully understood or emotionally absorbed over time.",am:"ነገር ቀስ ቀስ ሙሉ ለሙሉ ሲረዳ ወይም ሲሰማ",examples:["It took several weeks for the news of her acceptance to fully sink in — it felt surreal.","New vocabulary doesn't immediately sink in; it requires repeated exposure across multiple contexts."]},
  {pv:"spell out",sep:"sep",meaning:"To explain something very clearly and in detail.",am:"ነገርን ዝርዝር ሆኖ ቀጥ ብሎ ማብራራት",examples:["The instructions need to be spelled out in much simpler language for non-technical users to follow.","He had to spell out exactly what the contract required, because the language was extremely ambiguous."]},
  {pv:"sum up",sep:"sep",meaning:"To give a concise statement of the main points.",am:"ዋና ዋና ነጥቦቹን አጭር ሆኖ ማጠቃለል",examples:["To sum up, consistent daily practice is the single most effective strategy for language acquisition.","She summed up three hours of complex testimony in just a few clear, powerful sentences."]},
  {pv:"wade through",sep:"insep",meaning:"To work slowly and laboriously through something large or difficult.",am:"ትልቅ ወይም ፈታኝ ሥራ ቀስ ብሎ ሳይሸሹ ማካሄድ",examples:["She spent a whole weekend wading through hundreds of academic papers to find relevant sources.","Learning to wade through dense, complex English texts is a skill that improves dramatically with practice."]},
  {pv:"weigh up",sep:"sep",meaning:"To consider and compare the advantages and disadvantages of something.",am:"ጥቅምና ጉዳቱን አወዳድሮ ማሰብ",examples:["Before making any major decision, you must carefully weigh up all the potential benefits and risks involved.","She spent weeks weighing up the two job offers, considering everything from salary to work-life balance."]},
  {pv:"write off",sep:"sep",meaning:"To dismiss or consider something as a loss; to decide something has no future.",am:"ነገርን ጠፍቶ ወይም ዋጋ ቢስ ሆኖ ማሰናበት",examples:["Don't write off a career path simply because you failed on the first attempt — persistence matters.","The accountant wrote off the unpaid debt as an irrecoverable loss at the end of the financial year."]}
];
'@

# Find the PHRASAL block in the file
$startIdx = $content.IndexOf("const PHRASAL = [")
$searchFrom = $startIdx + 17
$bracketCount = 1
$i = $searchFrom
while ($i -lt $content.Length -and $bracketCount -gt 0) {
    if ($content[$i] -eq '[') { $bracketCount++ }
    elseif ($content[$i] -eq ']') { $bracketCount-- }
    $i++
}
# now $i points right after the closing ]
while ($i -lt $content.Length -and $content[$i] -ne ';') { $i++ }
$endIdx = $i + 1  # include the semicolon

$before = $content.Substring(0, $startIdx)
$after  = $content.Substring($endIdx)
$newContent = $before + $newPhrasal.TrimEnd() + $after

[System.IO.File]::WriteAllText($file, $newContent, [System.Text.Encoding]::UTF8)
Write-Host "Done! PHRASAL block updated with Amharic meanings."
Write-Host "New file length: $($newContent.Length)"
